#!/bin/sh

IFS=$'\n\t'
FILES="
	/etc/X11/xorg.conf.d/keyboard.conf
	/etc/X11/xorg.conf.d/monitor.conf
	/etc/X11/xorg.conf.d/mouse.conf
	/etc/X11/xorg.conf.d/screen-blank.conf
	/etc/X11/xorg.conf.d/touchpad.conf
	/etc/bash/bashrc.d/utils.bash
	/etc/bash/bashrc.d/qemu.bash
	/etc/cron.weekly/trim.sh
	/etc/env.d/90xsession
	/etc/fstab
	/etc/hostname
	/etc/hosts
	/etc/i3/config
	/etc/i3status.conf
	/etc/inittab
	/etc/modprobe.d/blacklist.conf
	/etc/ntp.conf
	/etc/polkit-1/rules.d/backlight.rules
	/etc/polkit-1/rules.d/conservation-mode.rules
	/etc/portage/make.conf
	/etc/portage/package.accept_keywords/steam-launcher
	/etc/portage/package.accept_keywords/sublime-text
	/etc/portage/package.use/cups-filters
	/etc/portage/package.use/firefox
	/etc/portage/package.use/hplip
	/etc/portage/package.use/iproute2
	/etc/portage/package.use/libreoffice
	/etc/portage/package.use/nvidia-drivers
	/etc/portage/package.use/openrc
	/etc/portage/package.use/qemu
	/etc/portage/package.use/steam-launcher
	/etc/sysctl.d/local.conf
	/etc/syslog.conf
	/etc/timezone
	/etc/udev/rules.d/power-supply.rules
	/etc/udev/rules.d/rfkill.rules
	/etc/udev/rules.d/runtime-pm.rules
	/etc/xdg/picom.conf
	/home/default/.bash_profile
	/home/default/.config/sublime-text/Packages/User/Default (Linux).sublime-mousemap
	/home/default/.config/sublime-text/Packages/User/Default (Linux).sublime-keymap
	/home/default/.config/sublime-text/Packages/User/Preferences.sublime-settings
	/home/default/.mozilla/firefox/*.default-esr/user.js
	/var/lib/portage/world
"
mkdir backup && cp --parents --recursive $FILES backup/ && chown -R default:users backup/
